Repository ucsb-cs156-m23/proj-happycows-m23-10am-3, pull requests merged in 2023-08, with the labels that each got.

#16 Create database table for commonStats
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonStats.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonStatsRepository.java
Labels: 5

#17 Removed toast message when purchasing cows
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 5

#19 Trivial changes to optimize the workflow
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
Labels: 5

#22 changed degradation 0.01 to 0.001
  frontend/src/main/components/Commons/CommonsForm.js
Labels: 5

#23 Changed cow health and milking updates to America/Los_Angeles time
  src/main/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobs.java
Labels: 5

#24 [Andrew] Format Leaderboard Wealth to Currency
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
Labels: 5

#26 added the capacityPerUser in entities and models for crating parameters
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
Labels: 5

#33 Common stats job
  src/main/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJob.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobFactory.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobs.java
  src/main/resources/application-development.properties
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobFactoryTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/CommonStatsJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/ScheduledJobsTests.java
Labels: 10

#25 [Andrew] Narrow Create Commons Form UI
  frontend/src/main/components/Commons/CommonsForm.js
Labels: 10

#35 Common stats endpoint
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
Labels: 5

#37 Common stats csv
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/helpers/CommonStatsCSVHelper.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonStatsRepository.java
  src/main/java/edu/ucsb/cs156/happiercows/services/AverageCowHealthService.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: MergeCandidate-Waiting on CI

#39 Common stats front end
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: READY for staff review

#49 add leaderboard back button
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 5

#60 Add computeEffectiveCapacity and relvelent changes
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/CommonsPlus.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJob.java
  src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategies.java
  src/main/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategy.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsPlusTest.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTest.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/strategies/CowHealthUpdateStrategyTests.java
Labels: PRIORITY

#58 update profit controller: get the profit with page number and page size
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
Labels: READY for staff review, 10

#47 [Andrew] Add capacityPerUser to Create + Edit pages
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
Labels: PRIORITY, READY for staff review

#61 [Andrew] Fixed Degradation Rate Steps to 0.001
  frontend/src/main/components/Commons/CommonsForm.js
Labels: PRIORITY, READY for staff review

#62 List commons shows capacityPerUser and effectiveCapacity
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: READY for staff review, 10
